name: Merge a develop con validación de pruebas

on:
  push:
    branches:
      - develop

jobs:
  merge-a-develop:
    name: Merge a develop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Crear rama feature
        run: git checkout -b feature/Merge_a_develop_con_validacion_de_pruebas

      - name: Fusionar cambios a develop
        run: git merge develop

      - name: Instalar herramientas de GitHub
        run: |
          sudo apt-get install -y hub

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
            python-version: '3.7'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar pruebas
      - name: Ejecutar pruebas
        run: |
          python -m unittest tests/test_album.py
        continue-on-error: true
        id: test_result

      - name: Verificar resultado de las pruebas
        if: ${{ failure() }}
        run: |
          echo "Las pruebas fallaron. No se realizará el merge."
          exit 1

      # Fusionar cambios a la rama main si las pruebas fueron exitosas
      - name: Fusionar cambios a main
        if: steps.test_result.outcome == 'success'
        run: |
          git push origin feature/Merge_a_develop_con_validacion_de_pruebas
          hub pull-request -b main -m "Merge a main con validación de pruebas exitosas" -h feature/Merge_a_develop_con_validacion_de_pruebas
